version: "3.8"
services:
  postgres:
    build: .
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # app:
  #   build:
  #     context: ./apps
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000" # Port for frontend
  #     - "5000:5000" # Port for backend
  #   volumes:
  #     - ./apps:/app # Optional: Mount your source code into the container for development
  #   # env_file:
  #   #   - ./apps/backend/.env
  #   environment:
  #     - NODE_ENV=production # Set your environment variables
  #     - BACKEND_PORT=5000
  #     - FRONTEND_PORT=3000
  #   depends_on:
  #     - postgres
  #   entrypoint: /app/backend/entrypoint.sh

volumes:
  postgres_data:
