export { default as Error } from "./Error"
export { default as ZCULogo } from "./ZCU"
export { default as Logout } from "./Logout"
export { default as Edit } from "./Edit"
// export { default as Delete } from "./Delete"
// export { default as Add } from "./Add"
// export { default as Arrow } from "./Arrow"
// export { default as Search } from "./Search"
// export { default as Close } from "./Close"
